SELECT 1a
SELECT a = 15
SELECT 'a' = 15

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = N'ACCOUNT'

CREATE DATABASE testDB;

DROP DATABASE testDB;

BACKUP DATABASE testDB
TO DISK = 'D:\backups\testDB.bak';