//-------------------------------------------------------------------------------------------------------------------------------------|
//  - AngularJS services are substitutable objects that are wired together using dependency injection (DI). You can use services 
//    to organize and share code across your app.
//
//  - AngularJS services are:
//      Lazily instantiated – AngularJS only instantiates a service when an application component depends on it.
//      Singletons – Each component dependent on a service gets a reference to the single instance generated by the service factory. 
//  - Both .service() and .factory() are both singletons as you’ll only get one instance of each Service regardless of what API 
//    created it.
//  - Remember that .service() is just a Constructor, it’s called with new, whereas .factory() is just a function that returns a value.
//  - Using .factory() gives us much more power and flexibility, whereas a .service() is essentially the “end result” of a .factory() 
//    call. The .service() gives us the returned value by calling new on the function, which can be limiting, whereas a .factory() is 
//    one-step before this compile process as we get to choose which pattern to implement and return.
//-------------------------------------------------------------------------------------------------------------------------------------|

var fnUserDataSvc = function ($http, $q) {

    var _users = [];
    var _user = {};

    var _getUsers = function (pagingRequest) {

        var promise = $http.post("http://localhost:5658/api/users", pagingRequest)
                .then(function (result) {
                    //Succes
                    return result.data.responseData;
                },
                function () {
                    //Error
                });
        return promise;
    };

    var _getUserCount = function () {
        var promise = $http.get("http://localhost:5658/api/users/count")
                        .then(function (result) {
                            //Succes
                            return result.data.responseData;
                        },
                        function () {
                            //Error
                        });
        return promise;
    };

    var _getUserSearch = function (keyword) {
        var promise = $http.get("http://localhost:5658/api/users/" + keyword + "/search")
                        .then(function (result) {
                            //Succes
                            return result.data;
                        },
                        function () {
                            //Error
                        });
        return promise;
    };

    var _getUserById = function (id) {

        var deferred = $q.defer();

        $http.get("http://localhost:5658/api/users/" + id)
        .then(function (result) {
            //Succes
            angular.copy(result.data, _user);
            deferred.resolve(result);
        },
        function () {
            deferred.reject();
        });

        return deferred.promise;
    };

    var _addUser = function (newUser) {
        var deferred = $q.defer();

        $http.post("http://localhost:5658/api/users/add", newUser)
        .then(function (result) {
            //success
            deferred.resolve();
        },
        function () {
            deferred.reject();
        });

        return deferred.promise;
    };

    var _editUser = function (user) {
        var deferred = $q.defer();

        $http.post("http://localhost:5658/api/users/edit", user)
        .then(function (result) {
            //success
            deferred.resolve();
        },
        function () {
            deferred.reject();
        });

        return deferred.promise;
    }

    var _deleteUser = function (userId) {
        var deferred = $q.defer();

        $http.post("http://localhost:5658/api/users/" + userId + "/delete")
        .then(function (result) {
            //success
            deferred.resolve();
        },
        function () {
            deferred.reject();
        });

        return deferred.promise;
    }

    return {
        Users: _users,
        User: _user,
        UserById: _getUserById,
        GetUsers: _getUsers,
        AddUser: _addUser,
        EditUser: _editUser,
        DeleteUser: _deleteUser,
        UserCount: _getUserCount,
        UserSearch: _getUserSearch
    };
};