// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using WineryStore.Persistence.Datastore;

namespace WineryStore.Persistence.Migrations
{
    [DbContext(typeof(WineryContext))]
    partial class WineryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WineryStore.Persistence.WineryContext+Wine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Color");

                    b.Property<string>("IssueDate");

                    b.Property<string>("Name");

                    b.Property<string>("Note");

                    b.Property<int>("Price");

                    b.Property<int>("Rank");

                    b.Property<int>("Score");

                    b.Property<string>("Vintage");

                    b.Property<Guid>("WineryId");

                    b.HasKey("Id");

                    b.HasIndex("WineryId");

                    b.ToTable("Wines");

                    b.HasData(
                        new { Id = new Guid("9293677d-a36b-46ce-b2a0-9173858156eb"), Color = 0, IssueDate = "Nov 30, 2017", Name = "Merlot Napa Valley Three Palms Vineyard", Note = "A powerful red, with concentrated flavors of red plum, cherry and boysenberry that are layered with plenty of rich spice and mineral accents. Touches of slate and cardamom make for a complex finish. Drink now through 2023. 3,170 cases made.", Price = 98, Rank = 1, Score = 95, Vintage = "2014", WineryId = new Guid("b3dc052c-c3a2-4607-9ca5-20e6deda3fc2") },
                        new { Id = new Guid("961bd0d0-a0eb-43c8-b076-441e47fdc847"), Color = 0, IssueDate = "Jul 31, 1989", Name = "Cabernet Sauvignon Napa Valley", Note = "On first sniff, this reveals itself as the complex wine it is, with smooth texture and deep plum, cherry, tar and vanilla flavors, long and perfumed. Drinkable now. 4,000 cases made.", Price = 18, Rank = 32, Score = 94, Vintage = "1986", WineryId = new Guid("b3dc052c-c3a2-4607-9ca5-20e6deda3fc2") },
                        new { Id = new Guid("18cc07e8-712e-4830-bceb-26f75f2ad3ab"), Color = 4, IssueDate = "Mar 31, 2017", Name = "Barsac", Note = "This shows the vivid, racy side of Barsac, with streaming flavors of pineapple, yellow apple, green plum and white ginger, displaying lovely energy from start to finish. Ends with enough honeysuckle and orange blossom notes to balance the richness. Best from 2020 through 2035. 4,000 cases made.", Price = 37, Rank = 3, Score = 96, Vintage = "2014", WineryId = new Guid("0a634ffd-874b-4796-8875-02181b0ebcc8") },
                        new { Id = new Guid("05e45cf9-fefc-408c-97a0-81b3598ef415"), Color = 0, IssueDate = "Jun 15, 2017", Name = "Brunello di Montalcino", Note = "Effusive aromas and flavors of raspberry, cherry, floral, mineral and tobacco are at the center of this linear, vibrant red. Well-structured, this offers terrific length on the sinewy finish. Best from 2020 through 2035. 6,054 cases made.", Price = 65, Rank = 4, Score = 95, Vintage = "2012", WineryId = new Guid("b39c7530-622d-456e-afb6-760f3653f076") },
                        new { Id = new Guid("9c2e678d-9af2-48fa-a2be-40b6238c5dce"), Color = 1, IssueDate = "Jun 15, 2015", Name = "Valdeorras ViÃ±a Godeval Cepas Vellas", Note = "This alluring white delivers a broad range of flavors in a pillowy texture, while crisp, well-integrated acidity maintains the focus. Melon, coconut, spice and smoke flavors mingle harmoniously on the plush palate. The mineral element is fresh and long. Godello. Drink now through 2018. 1,800 cases imported.", Price = 20, Rank = 36, Score = 92, Vintage = "2013", WineryId = new Guid("2e085a4d-a5d8-4352-8908-1b2103437885") },
                        new { Id = new Guid("dc8fdc32-b96b-4ea6-a4c9-f2514b183a53"), Color = 1, IssueDate = "Sep 30, 2016", Name = "Valdeorras ViÃ±a Godeval Cepas Vellas", Note = "Pear, peach and quince flavors mingle in this expressive white, while notes of mineral, tangerine and ginger add complexity. Shows depth and focus, with a clean, juicy finish. Drink now. 1,800 cases imported.", Price = 20, Rank = 75, Score = 91, Vintage = "2014", WineryId = new Guid("2e085a4d-a5d8-4352-8908-1b2103437885") },
                        new { Id = new Guid("a05164df-2bdb-4675-9afa-9f5cbd9e69bd"), Color = 0, IssueDate = "Jun 15, 2018", Name = "Rasa Shiraz", Note = "It is a complex wine, with power and finesse. Crafted from handpicked grapes from our own estate vineyards, Rasa Shiraz is aged for 12 months in premium French oak barrels and then further matured in the bottle before release.", Price = 20, Rank = 36, Score = 92, Vintage = "2015", WineryId = new Guid("d2835e85-89ab-4b23-a5d5-48db93f778dd") },
                        new { Id = new Guid("60e79b55-b2e8-45f7-9b89-6f9de315d12e"), Color = 1, IssueDate = "Sep 30, 2017", Name = "Dindori Reserve Viognier", Note = "Dindori Reserve Viognier is an exotic elixir of peach and lychee flavours. Floral, spicy, stunning. Great as an aperitif and terrific with spicy food. Serve well chilled.", Price = 20, Rank = 75, Score = 91, Vintage = "2014", WineryId = new Guid("d2835e85-89ab-4b23-a5d5-48db93f778dd") },
                        new { Id = new Guid("8610c9aa-704e-4a10-99f3-086b980a8c4f"), Color = 2, IssueDate = "Sep 30, 2016", Name = "Zinfandel Rosé", Note = "Zinfandel Rose is ripe, fresh and fruity, with abundant aromas of cranberries and fresh strawberries. A versatile “anytime” wine great for picnics, parties and hot summer days. Lovely with poultry and spicy dishes. Serve well chilled.", Price = 16, Rank = 100, Score = 91, Vintage = "2015", WineryId = new Guid("d2835e85-89ab-4b23-a5d5-48db93f778dd") },
                        new { Id = new Guid("d9272018-dae4-4f1a-badf-b195c27bb057"), Color = 5, IssueDate = "Sep 30, 2019", Name = "Brut", Note = "A complex blend of Chenin Blanc, Chardonnay, Viognier, Pinot Noir, Riesling and Shiraz. This is one of the few “Méthode Champenoise” wines in the world to be crafted from six different grapes, resulting in something remarkable", Price = 41, Rank = 12, Score = 91, Vintage = "2017", WineryId = new Guid("d2835e85-89ab-4b23-a5d5-48db93f778dd") },
                        new { Id = new Guid("9fb0680a-582c-4aa8-ae7f-21464b5bc5ca"), Color = 4, IssueDate = "Sep 30, 2019", Name = "Late Harvest Chenin Blanc", Note = "Abounding with aromas of mango, honey and tropical fruit, our award winning Late Harvest Chenin Blanc is the perfect close to a delicious meal, but is also an elegant aperiti", Price = 15, Rank = 5, Score = 91, Vintage = "2019", WineryId = new Guid("d2835e85-89ab-4b23-a5d5-48db93f778dd") }
                    );
                });

            modelBuilder.Entity("WineryStore.Persistence.WineryContext+Winery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Country");

                    b.Property<string>("Name");

                    b.Property<string>("Region");

                    b.HasKey("Id");

                    b.ToTable("Wineries");

                    b.HasData(
                        new { Id = new Guid("b3dc052c-c3a2-4607-9ca5-20e6deda3fc2"), Country = "California", Name = "Duckhorn", Region = "Napa" },
                        new { Id = new Guid("0a634ffd-874b-4796-8875-02181b0ebcc8"), Country = "France", Name = "Château Coutet", Region = "Bordeaux" },
                        new { Id = new Guid("b39c7530-622d-456e-afb6-760f3653f076"), Country = "Italy", Name = "Casanova di Neri", Region = "Tuscany" },
                        new { Id = new Guid("2e085a4d-a5d8-4352-8908-1b2103437885"), Country = "Spain", Name = "Bodegas Godeval", Region = "Spain" },
                        new { Id = new Guid("d2835e85-89ab-4b23-a5d5-48db93f778dd"), Country = "India", Name = "Sula", Region = "Nashik" }
                    );
                });

            modelBuilder.Entity("WineryStore.Persistence.WineryContext+Wine", b =>
                {
                    b.HasOne("WineryStore.Persistence.WineryContext+Winery", "WineryRelation")
                        .WithMany("Wines")
                        .HasForeignKey("WineryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
